language: python
python: 3.5
addons:
  - postgresql: "9.4"

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install gfortran gnuplot wget
  - git submodule update --init
  - cd ./mercury
  - ./compile.sh
  - cd -
  - pip install -r reqs.pip
  - pip install coverage pytest==2.8.3

before_script:
  - cd ./catalog
  - wget http://hamilton.dm.unipi.it/~astdys2/catalogs/allnum.cat
  - cd -
  - mkdir axis
  - cd axis
  - wget https://raw.githubusercontent.com/smirik/Three-body-resonances/master/axis/resonances
  - cd -
  - psql -c 'create database resonances;' -U postgres
  - cp alembic.ini.dist alembic.ini
  - sed -i.bak -r -e 's/^# sqlalchemy.url(.*)/sqlalchemy.url = postgresql:\/\/postgres@localhost\/resonances/g' alembic.ini
  - alembic upgrade head

script:
  - python ./main.py calc
  - python ./main.py package --res=1 --compress=1 --aei=1
  - python ./main.py find
  - cat ./export/full.db | wc -l
  - python -m unittest discover -v -p '*.py' ./tests
  - python -m pytest ./tests/entitiestest/librationtest.py ./tests/utils_tests.py

#after_success:
#  - coverage report -m
