language: python
python: 3.5
sudo: false
addons:
  postgresql: "9.4"
  apt:
    packages:
      - gfortran
      - gnuplot
      - wget
      - redis

services:
  - redis

install:
  - git submodule update --init
  - cd ./mercury
  - ./compile.sh
  - cd -
  - pip install -r reqs.pip
  - pip install coverage pytest==2.8.3

before_script:
  - cd ./catalog
  - wget http://hamilton.dm.unipi.it/~astdys2/catalogs/allnum.cat
  - cd -
  - mkdir axis
  - cd axis
  - wget https://raw.githubusercontent.com/smirik/Three-body-resonances/master/axis/resonances
  - cd -
  - psql -c 'create database resonances;' -U postgres
  - psql -c 'create database resonances_unittest;' -U postgres
  - cp alembic.ini.dist alembic.ini
  - cp alembic.ini.dist alembic.test.ini
  - sed -i.bak -r -e 's/^# sqlalchemy.url(.*)/sqlalchemy.url = postgresql:\/\/postgres@localhost\/resonances/g' alembic.ini
  - sed -i.bak -r -e 's/^# sqlalchemy.url(.*)/sqlalchemy.url = postgresql:\/\/postgres@localhost\/resonances_unittest/g' alembic.test.ini
  - alembic upgrade head
  - alembic -c ./alembic.test.ini upgrade head

script:
  - python ./main.py calc
  - python ./main.py package --res=1 --compress=1 --aei=1
  - python ./main.py find --reload-resonances=1
  - cat ./export/full.db | wc -l
  - coverage run --omit='/home/travis/virtualenv/*,./tests/*' -m pytest `find ./tests -name '*.py'`

after_success:
  - coverage report -m
