debug: false

db_path: 'alembic.ini'

resonance_table:
  format: simple
  file: resonances
  
catalog:
  file: catalog/allnum.cat
  type: astdys
  
  astdys:
    skip: 6

integrator:
  type: mercury6
  input: input/mercury
  
  dir: mercury
  
  files:
    small_bodies: small.in

  start: 2455400.5
  step:  3650.25
  number_of_bodies: 100

resonance:
  libration:
    min: 20000
  db_file: export/full.db
  bodies_numbers:
    - 5
    - 6

phases_dir: '.phases_dir'
extract_dir: '.from_archives'
s3files_dir: '.s3files_dir'

output:
  angle:   output/res
  gnuplot: output/gnu
  images:  output/images

  format:  png

export:
  base_dir: export
  aei_dir:  aei
  structure:
    - aei
    - mercury
    - res
    - png
    - resonances
    - gnu

gnuplot:
  x_stop: 100000
  type:   points
  
constants:
  u:  0.0002959122082855911025
  k:  0.017202098795
  k2: 0.0002959122082855911025

  planets:
    - 0.0                   # sun
    - 1.66014780554019e-07  # mercury
    - 2.44733799205671e-06  # venus
    - 3.00316726157559e-06  # earth
    - 3.22683625760394e-07  # mars
    - 0.000954502036096727  # jupiter
    - 0.000285787542104469  # saturn
    - 4.36378261525313e-05  # uranus
    - 5.14956512995827e-05  # neptune
    - 6.56075612085868e-09  # pluto ?

  axis:
    - 0.0           # sun
    - 0.0           # mercury
    - 0.723332      # venus
    - 1.00000261    # earth
    - 1.523679      # mars
    - 5.204267      # jupiter
    - 9.58201720    # saturn
    - 19.19126393   # uranus
    - 30.06896348   # neptune
  mean_motion: # in seconds (sec)
    - 0.0               # sun
    - 0.0               # mercury
    - 2106626.16642123  # venus
    - 1297281.96342998  # earth
    - 689017.369124865  # mars
    - 109256.679        # jupiter
    - 43995.910         # saturn
    - 15414.596         # uranus
    - 7859.770          # neptune
  longitude_of_periapsis:
    - 0.0       # sun
    - 0.0       # mercury
    - 7.452     # venus
    - 17.368    # earth
    - 17.916    # mars
    - 4.257     # jupiter
    - 28.243    # saturn
    - 3.088     # uranus
    - 0.673     # neptune

redis:
  host: localhost
  port: 6379
  db: 0

postgres:
  host: $POSTGRES_PORT_5432_TCP_ADDR
  user: $RESONANCES_DB_USER
  password: $POSTGRES_ENV_POSTGRES_PASSWORD
  db: $RESONANCES_DB_NAME

s3:
  access_key: $S3_ACCESS_KEY
  secret_key: $S3_SECRET_KEY
  bucket: $S3_BUCKET
